# Generated by Django 4.1.5 on 2023-03-22 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meals.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandardIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity')),
                ('unit', models.CharField(max_length=20, validators=[meals.validators.MealValidators.is_valid_unit], verbose_name='Unit')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('num_servings', models.PositiveIntegerField(verbose_name='Number of Servings')),
                ('rating', models.PositiveIntegerField(validators=[meals.validators.MealValidators.is_valid_rating], verbose_name='Rating')),
                ('cook_time', models.PositiveIntegerField(verbose_name='Cooking Time')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity')),
                ('unit', models.CharField(max_length=20, validators=[meals.validators.MealValidators.is_valid_unit], verbose_name='Unit')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('date', models.DateField(verbose_name='Date')),
                ('currency', models.CharField(max_length=3, validators=[meals.validators.MealValidators.is_valid_currency], verbose_name='Currency')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.fooditem')),
            ],
        ),
    ]
