# Generated by Django 4.1.5 on 2023-02-01 11:09

from django.db import migrations, models
import django.db.models.deletion
import meals.validators


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity')),
                ('unit', models.CharField(max_length=20, validators=[meals.validators.MealValidators.is_valid_unit], verbose_name='Unit')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('date', models.DateField(verbose_name='Date')),
                ('currency', models.CharField(max_length=3, validators=[meals.validators.MealValidators.is_valid_currency], verbose_name='Currency')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.fooditem')),
            ],
        ),
    ]
