# Generated by Django 4.1.5 on 2023-02-01 11:58

from django.db import migrations, models
import django.db.models.deletion
import meals.validators


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_foodpricerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity')),
                ('unit', models.CharField(max_length=20, validators=[meals.validators.MealValidators.is_valid_unit], verbose_name='Unit')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
    ]
