# Generated by Django 4.1.5 on 2023-02-01 12:22

from django.db import migrations, models
import django.db.models.deletion
import meals.validators


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_standardingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('num_servings', models.PositiveIntegerField(verbose_name='Number of Servings')),
                ('rating', models.PositiveIntegerField(validators=[meals.validators.MealValidators.is_valid_rating], verbose_name='Rating')),
                ('cook_time', models.PositiveIntegerField(verbose_name='Cooking Time')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
    ]
